// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/aarondever/go-gin-template/internal/model"
)

type CreateUserInput struct {
	Name  string  `json:"name"`
	Email *string `json:"email,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateUserInput struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
}

type UserConnection struct {
	Users []*model.User `json:"users"`
	Total int           `json:"total"`
}

type UserListInput struct {
	Name   *string `json:"name,omitempty"`
	Limit  *int32  `json:"limit,omitempty"`
	Offset *int32  `json:"offset,omitempty"`
}
