// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/aarondever/go-gin-template/internal/config"
	"github.com/aarondever/go-gin-template/internal/database"
	"github.com/aarondever/go-gin-template/internal/handlers"
	"github.com/aarondever/go-gin-template/internal/services"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

// InitializeApp uses Wire to initialize all dependencies
func InitializeApp(cfg *config.Config) (*App, error) {
	databaseDatabase, err := database.NewDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userService := services.NewUserService(cfg, databaseDatabase)
	userHandler := handlers.NewUserHandler(userService)
	app := NewApp(databaseDatabase, userHandler)
	return app, nil
}

// wire.go:

type App struct {
	DB     *database.Database
	Router *gin.Engine
}

func NewApp(
	db *database.Database,
	userHandler *handlers.UserHandler,

) *App {
	router := gin.Default()

	userHandler.SetupRouters(router)

	return &App{
		DB:     db,
		Router: router,
	}
}
